import type { Metadata } from "next";
import robotoMono from "./fonts/roboto_mono";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${robotoMono.className}`}>
        {children}
      </body>
    </html>
  );
}
